#!/usr/bin/env python3
"""
html2header.py - Minify HTML → Gzip → C++ Header (Arduino PROGMEM)
Supports inline CSS/JS minification via rcssmin/rjsmin.
Falls back to built-in regex if htmlmin is absent (Python 3.13 safe).
"""

import gzip
import os
import re
import sys
import argparse
from datetime import datetime

INPUT_HTML = 'index.html'
OUTPUT_HEADER = 'WebPage.h'
OUTPUT_MINIFIED = 'index.min.html'

# ---------- Built-in fallback minifiers ----------
def minify_html_builtin(html_str):
    html_str = re.sub(r'<!--.*?-->', '', html_str, flags=re.DOTALL)
    html_str = re.sub(r'>\s+<', '><', html_str)
    html_str = re.sub(r'\s{2,}', ' ', html_str)
    return html_str.strip()

def minify_css_builtin(css_str):
    css_str = re.sub(r'/\*.*?\*/', '', css_str, flags=re.DOTALL)
    css_str = re.sub(r'\s*([{}:;,])\s*', r'\1', css_str)
    css_str = re.sub(r';\s*}', '}', css_str)
    css_str = re.sub(r'[\n\r\t]', ' ', css_str)
    css_str = re.sub(r'\s{2,}', ' ', css_str)
    return css_str.strip()

def minify_js_builtin(js_str):
    js_str = re.sub(r'//.*$', '', js_str, flags=re.MULTILINE)
    js_str = re.sub(r'/\*.*?\*/', '', js_str, flags=re.DOTALL)
    js_str = re.sub(r'\s+', ' ', js_str)
    js_str = re.sub(r'\s*([=+\-*/<>!&|?:;,{}()[\]])\s*', r'\1', js_str)
    return js_str.strip()

# ---------- Main processor ----------
def process_html(input_path, aggressive=False):
    with open(input_path, 'r', encoding='utf-8') as f:
        html = f.read()

    original_size = len(html.encode('utf-8'))

    # Try importing advanced libraries
    USE_HTMLMIN = USE_RCSSMIN = USE_RJSMIN = False
    try:
        # pyrefly: ignore [missing-import]
        import htmlmin
        USE_HTMLMIN = True
    except ImportError:
        print("Note: 'htmlmin' not installed → using built-in regex for HTML.")

    try:
        import rcssmin
        USE_RCSSMIN = True
    except ImportError:
        print("Note: 'rcssmin' not installed → using basic CSS minification.")

    try:
        import rjsmin
        USE_RJSMIN = True
    except ImportError:
        print("Note: 'rjsmin' not installed → using basic JS minification.")

    # Minify inline <style>
    def replace_style(match):
        css = match.group(1)
        if USE_RCSSMIN:
            css = rcssmin.cssmin(css)
        else:
            css = minify_css_builtin(css)
        return f'<style>{css}</style>'

    # Minify inline <script>
    def replace_script(match):
        js = match.group(1)
        if USE_RJSMIN:
            js = rjsmin.jsmin(js)
        else:
            js = minify_js_builtin(js)
        return f'<script>{js}</script>'

    html = re.sub(r'<style[^>]*>(.*?)</style>', replace_style, html, flags=re.DOTALL)
    html = re.sub(r'<script[^>]*>(.*?)</script>', replace_script, html, flags=re.DOTALL)

    # Global HTML minify
    if USE_HTMLMIN:
        minified = htmlmin.minify(html,
                                  remove_comments=True,
                                  remove_empty_space=True,
                                  remove_all_empty_space=aggressive,
                                  reduce_boolean_attributes=True,
                                  remove_optional_attribute_quotes=aggressive)
    else:
        minified = minify_html_builtin(html)

    minified_size = len(minified.encode('utf-8'))
    return minified, original_size, minified_size

# ---------- Compress & Generate Header ----------
def compress_and_convert(input_path, output_header, output_minified=None, aggressive=False):
    if not os.path.exists(input_path):
        print(f"Error: '{input_path}' not found!")
        sys.exit(1)

    minified_html, orig_size, mini_size = process_html(input_path, aggressive)

    if output_minified:
        with open(output_minified, 'w', encoding='utf-8') as f:
            f.write(minified_html)
        print(f"Test minified HTML → {output_minified}")

    # Gzip compress
    compressed_data = gzip.compress(minified_html.encode('utf-8'))
    gz_size = len(compressed_data)

    # Build C array
    hex_list = [f"0x{b:02X}" for b in compressed_data]
    formatted_hex = ""
    for i in range(0, len(hex_list), 16):
        line = ", ".join(hex_list[i:i+16])
        formatted_hex += f"    {line},\n"
    formatted_hex = formatted_hex.rstrip(",\n")

    current_time = datetime.now().strftime("%Y-%m-%d %I:%M:%S %p")

    # Header content with all sizes
    header_content = f"""/**
 * @file {output_header}
 * @brief Auto-generated Gzipped HTML for PROGMEM
 * @date {current_time}
 *
 * Size summary:
 *   Original (UTF-8)    : {orig_size} bytes
 *   Minified            : {mini_size} bytes
 *   Gzip compressed     : {gz_size} bytes
 *   Total saving        : {100 - (gz_size/orig_size*100):.1f}%
 *
 * @warning This file is auto-generated by html2header.py and should not be edited manually.
 * @note To update this file, edit index.html and run html2header.py again.
 * @note Powered by html2header.py (made by AdaCodec)
 */

#ifndef WEBPAGE_H
#define WEBPAGE_H

#include <Arduino.h>

const uint8_t index_html_gz[] PROGMEM = {{
{formatted_hex}
}};

const size_t index_html_gz_len = {gz_size};

#endif // WEBPAGE_H
"""

    with open(output_header, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print("-" * 50)
    print("✅ Conversion Successful!")
    print(f"   Original : {orig_size:>8} bytes")
    print(f"   Minified : {mini_size:>8} bytes")
    print(f"   Gzipped  : {gz_size:>8} bytes")
    print(f"   Saving   : {100 - (gz_size/orig_size*100):.1f}%")
    print("-" * 50)
    print(f"Header  → {output_header}")
    if output_minified:
        print(f"Preview → {output_minified}")

# ---------- CLI ----------
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Convert HTML to Gzipped C++ Header")
    parser.add_argument('--input', default=INPUT_HTML, help="Input HTML file")
    parser.add_argument('--header', default=OUTPUT_HEADER, help="Output .h file")
    parser.add_argument('--minified', default=OUTPUT_MINIFIED, help="Output minified HTML (for testing)")
    parser.add_argument('--aggressive', action='store_true', help="Aggressive minification (may break layout!)")
    args = parser.parse_args()

    compress_and_convert(args.input, args.header, args.minified, args.aggressive)